language: objective-c
osx_image: xcode7.2
xcode_workspace: DungeonsDragonsCC.xcworkspace
xcode_scheme: DungeonsDragonsCCTravis
xcode_sdk: iphonesimulator9.2
script:
  - xcodebuild test -workspace DungeonsDragonsCC.xcworkspace -scheme DungeonsDragonsCCTravis -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- pod install