language: swift
osx_image: xcode8
xcode_workspace: DungeonsDragonsCC.xcworkspace
xcode_scheme: DungeonsDragonsCCTravis
xcode_sdk: iphonesimulator10.0
script:
  - xcodebuild test -workspace DungeonsDragonsCC.xcworkspace -scheme DungeonsDragonsCCTravis -destination 'platform=iOS Simulator,name=iPhone 6'
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- pod install
