language: objective-c
osx_image: xcode10
xcode_workspace: DungeonsDragonsCC.xcworkspace
xcode_scheme: DungeonsDragonsCCTravis
xcode_sdk: iphonesimulator10
script:
  - xcodebuild test -workspace DungeonsDragonsCC.xcworkspace -scheme DungeonsDragonsCCTravis -destination 'platform=iOS Simulator,name=iPhone 6'
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- pod install
